### ISSUE TITLE
Open the Nitrious Link Please

### ISSUE THREAD

**Issue by alberto3206** [learn-co-curriculum/bash-navigation-nitrous#6]
Hey,

I closed nitrous in the previous lesson. I wanted to re-open it but the option wasn't available. This may have been intentional to have me problem solve. If not, please allow for the link on the learn.co website to allow it. 

Thanks,
Alberto

**Comment by sammarcus** [comment]
Hey @alberto3206! Sorry about the trouble you're having. Lessons that don't have the Nitrous button are not actual coding labs, but rather just reading labs. If you'd like to open Nitrous, please navigate back to that lab or any lab that is a coding lab and the button should reappear. It will never appear on "instructional" labs such as this one (we call them Readme's).

In the future for more immediate help, if you click the Ask a Question button someone will see your request and send you an immediate reply :)

Thanks!
